name: x_physics
description: X-Physics Flutter app for interactive Physics learning.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  provider: ^6.1.1
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
