export const chapters = [
  {
    id: 1,
    title: "Chuyển động cơ học",
    icon: "🚀",
    color: "#2563EB",
    bgColor: "#DBEAFE",
    lessons: 5,
    progress: 80,
    description: "Tìm hiểu về chuyển động, vận tốc và quãng đường",
  },
  {
    id: 2,
    title: "Lực và áp suất",
    icon: "⚖️",
    color: "#7C3AED",
    bgColor: "#EDE9FE",
    lessons: 4,
    progress: 50,
    description: "Khám phá lực tác dụng, áp lực và áp suất",
  },
  {
    id: 3,
    title: "Điện học cơ bản",
    icon: "⚡",
    color: "#F59E0B",
    bgColor: "#FEF3C7",
    lessons: 6,
    progress: 17,
    description: "Hiệu điện thế, cường độ dòng điện và điện trở",
  },
];

export const lessons = [
  {
    id: 1,
    chapterId: 1,
    title: "Chuyển động đều",
    duration: 10,
    status: "completed" as const,
    score: 9,
    icon: "📏",
  },
  {
    id: 2,
    chapterId: 1,
    title: "Vận tốc trung bình",
    duration: 12,
    status: "completed" as const,
    score: 8,
    icon: "🏃",
  },
  {
    id: 3,
    chapterId: 1,
    title: "Chuyển động không đều",
    duration: 15,
    status: "in-progress" as const,
    score: null,
    icon: "🌀",
  },
  {
    id: 4,
    chapterId: 1,
    title: "Tính tương đối của chuyển động",
    duration: 10,
    status: "locked" as const,
    score: null,
    icon: "🔄",
  },
  {
    id: 5,
    chapterId: 1,
    title: "Bài tập tổng hợp",
    duration: 20,
    status: "locked" as const,
    score: null,
    icon: "📝",
  },
  {
    id: 6,
    chapterId: 2,
    title: "Lực là gì?",
    duration: 8,
    status: "completed" as const,
    score: 10,
    icon: "💪",
  },
  {
    id: 7,
    chapterId: 2,
    title: "Áp suất chất lỏng",
    duration: 12,
    status: "in-progress" as const,
    score: null,
    icon: "💧",
  },
  {
    id: 8,
    chapterId: 3,
    title: "Cường độ dòng điện",
    duration: 10,
    status: "in-progress" as const,
    score: null,
    icon: "⚡",
  },
];

export const quizQuestions = [
  {
    id: 1,
    question: "Một vật chuyển động đều với vận tốc 5 m/s. Sau 10 giây, vật đi được quãng đường bao nhiêu?",
    options: ["40 m", "50 m", "45 m", "55 m"],
    correct: 1,
    explanation: "Áp dụng công thức s = v × t = 5 × 10 = 50 m",
  },
  {
    id: 2,
    question: "Đơn vị của vận tốc trong hệ SI là gì?",
    options: ["km/h", "m/s", "cm/s", "m/min"],
    correct: 1,
    explanation: "Trong hệ SI, đơn vị vận tốc là mét trên giây (m/s)",
  },
  {
    id: 3,
    question: "Chuyển động nào sau đây là chuyển động đều?",
    options: [
      "Xe máy tăng tốc khi xuất phát",
      "Trái đất quay quanh mặt trời",
      "Kim đồng hồ chuyển động",
      "Viên đá rơi tự do",
    ],
    correct: 2,
    explanation: "Kim đồng hồ chuyển động với tốc độ góc không đổi, là chuyển động đều",
  },
  {
    id: 4,
    question: "Nếu một vật đi được 100 m trong 20 giây, vận tốc trung bình của vật là?",
    options: ["4 m/s", "5 m/s", "6 m/s", "8 m/s"],
    correct: 1,
    explanation: "v = s/t = 100/20 = 5 m/s",
  },
  {
    id: 5,
    question: "Tính tương đối của chuyển động có nghĩa là gì?",
    options: [
      "Vật luôn chuyển động so với mọi vật",
      "Chuyển động phụ thuộc vào vật được chọn làm mốc",
      "Vận tốc của vật luôn bằng nhau",
      "Vật đứng yên so với Trái Đất",
    ],
    correct: 1,
    explanation: "Trạng thái chuyển động hay đứng yên phụ thuộc vào vật mốc được chọn",
  },
];

export const badges = [
  { id: 1, name: "Nhà vật lý tập sự", icon: "🔬", earned: true },
  { id: 2, name: "Chinh phục chương 1", icon: "🏆", earned: true },
  { id: 3, name: "Điểm 10 hoàn hảo", icon: "⭐", earned: true },
  { id: 4, name: "7 ngày liên tiếp", icon: "🔥", earned: true },
  { id: 5, name: "Bậc thầy công thức", icon: "🧮", earned: false },
  { id: 6, name: "Chinh phục chương 2", icon: "🥇", earned: false },
  { id: 7, name: "Siêu sao vật lý", icon: "🌟", earned: false },
  { id: 8, name: "30 ngày liên tiếp", icon: "💎", earned: false },
];

export const quizHistory = [
  { date: "T2", score: 7.5 },
  { date: "T3", score: 8.0 },
  { date: "T4", score: 6.5 },
  { date: "T5", score: 9.0 },
  { date: "T6", score: 8.0 },
];
